// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYyVaXFYaXD8y1K7PQGg8698icTUR78g',
    appId: '1:284789984047:web:5e87fa4cf0a18fe9d4efda',
    messagingSenderId: '284789984047',
    projectId: 'newp-ca748',
    authDomain: 'newp-ca748.firebaseapp.com',
    storageBucket: 'newp-ca748.appspot.com',
    measurementId: 'G-S811PG2JJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMLi78A8DL5a1Z-8SmtGVYKibROZOrKk',
    appId: '1:284789984047:android:ea3af00ca6c71e4bd4efda',
    messagingSenderId: '284789984047',
    projectId: 'newp-ca748',
    storageBucket: 'newp-ca748.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQi5sxpvqdiuGt5KuYn1JGoJQkzprKKgo',
    appId: '1:284789984047:ios:ac768a71a018948bd4efda',
    messagingSenderId: '284789984047',
    projectId: 'newp-ca748',
    storageBucket: 'newp-ca748.appspot.com',
    iosBundleId: 'com.example.try2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQi5sxpvqdiuGt5KuYn1JGoJQkzprKKgo',
    appId: '1:284789984047:ios:ac768a71a018948bd4efda',
    messagingSenderId: '284789984047',
    projectId: 'newp-ca748',
    storageBucket: 'newp-ca748.appspot.com',
    iosBundleId: 'com.example.try2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhYyVaXFYaXD8y1K7PQGg8698icTUR78g',
    appId: '1:284789984047:web:ab97c0ea1af7dcf8d4efda',
    messagingSenderId: '284789984047',
    projectId: 'newp-ca748',
    authDomain: 'newp-ca748.firebaseapp.com',
    storageBucket: 'newp-ca748.appspot.com',
    measurementId: 'G-2R9BM40H6Q',
  );
}
